# dubbo-consumer
dubbo:
  application:
    name: mall-portal-web
    qos-enable: false
  registry:
    address: zookeeper://192.168.56.102:2181
  scan:
    base-packages: cn.com.service

# 端口
server:
  port: 8082

# 日志
logging:
  level:
    cn.com: debug

# 模板配置
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/