# dubbo-consumer
dubbo:
  application:
    name: mall-manager-web
    qos-enable: false
  registry:
    address: zookeeper://192.168.56.102:2181
  scan:
    base-packages: cn.com.service

# 端口
server:
  port: 8081
# 日志
logging:
  level:
    cn.com: debug